import {test,expect,_electron as electron,type ElectronApplication} from '@playwright/test';
import {createServer} from 'node:http';
import {mkdir,mkdtemp,writeFile} from 'node:fs/promises';
import {join} from 'node:path';
import {desktopRoot,output,startBrain} from './brain-fixture.js';
test('선제 제안 실제 Brain·모델 HTTP·UI·거절·출처 삭제·재시작과 실행 권한 독립',async()=>{
 test.setTimeout(90000);await mkdir(output,{recursive:true});const root=await mkdtemp(join(output,'proactive-')),profile=join(root,'profile');await mkdir(profile);
 const requests:any[]=[];const upstream=createServer(async(req,res)=>{let raw='';for await(const chunk of req)raw+=chunk;const body=JSON.parse(raw);requests.push(body);
  const source=JSON.parse(body.messages.at(-1).content)[0];res.setHeader('content-type','application/x-ndjson');
  res.end(JSON.stringify({model:body.model,message:{content:JSON.stringify({text:'발표 준비를 도와드릴까요?',source_id:source.source_id,quote:'발표 준비'})},done:true})+'\n');});
 await new Promise<void>(r=>upstream.listen(0,'127.0.0.1',r));const url='http://127.0.0.1:'+(upstream.address()as{port:number}).port;
 const model={provider_id:'ollama',model_id:'proactive-fixture',endpoint_id:'test-ollama'};
 const brain=await startBrain(url,model.model_id,'local',{data_dir:join(root,'brain'),bindings:[{model,label:'proactive-fixture',kind:'ollama',url,boundary:'local',automatic_allowed:true,budget_units:1,supports_text:true}]});
 const request=async(path:string,method='GET',body?:unknown)=>{const response=await fetch(brain.url+path,{method,headers:{Authorization:'Bearer '+brain.token,'Content-Type':'application/json'},...(body===undefined?{}:{body:JSON.stringify(body)})});expect(response.ok).toBe(true);return response.json();};
 const memory=(await request('/v1/sources','POST',{title:'검증용 발표 기억',text:'발표 준비 항목을 정리해야 한다.',kind:'memory',boundary:'local',parents:[]})).source;
 async function launch(){const env={...process.env,KIRIAN_DESKTOP_TEST:'1',KIRIAN_TEST_PROFILE:profile};for(const key of ['ELECTRON_RUN_AS_NODE','KIRIAN_BRAIN_URL','KIRIAN_BRAIN_TOKEN','KIRIAN_RENDERER_URL'])delete env[key];
  return electron.launch({cwd:desktopRoot,args:process.env.KIRIAN_PACKAGED_EXE?[]:[desktopRoot],executablePath:process.env.KIRIAN_PACKAGED_EXE,env,chromiumSandbox:true});}
 let app:ElectronApplication|undefined;
 try{app=await launch();let page=await app.firstWindow();
  await page.evaluate(options=>(window as any).kirianDesktop.connectBrain(options),{url:brain.url,token:brain.token});
  await expect(page.getByTestId('connection-status')).toHaveText('연결됨');
  await expect.poll(()=>page.evaluate(async()=>(await(window as any).kirianDesktop.getProactive()).available)).toBe(true);
  expect(requests.length).toBe(0);
  await page.getByTestId('proactive-panel').locator('summary').click();
  await page.getByRole('button',{name:'기억 목록 확인',exact:true}).click();
  await page.getByLabel('검증용 발표 기억',{exact:true}).check();await page.getByTestId('proactive-enabled').check();
  await page.getByTestId('proactive-save').click();await page.getByTestId('proactive-start').click();
  await expect(page.getByTestId('proactive-card')).toContainText('발표 준비를 도와드릴까요?',{timeout:15000});expect(requests.length).toBe(1);
  const state=await page.evaluate(()=>(window as any).kirianDesktop.getProactive());expect(state.cards[0].actualModel).toEqual(model);
  expect((await request('/v1/routing')).calls_used).toBe(1);
  expect(await page.evaluate(async()=>(await(window as any).kirianDesktop.getExternalState()).actions)).toEqual([]);
  expect(await page.evaluate(()=>(window as any).kirianDesktop.listActions())).toEqual([]);
  await page.getByTestId('proactive-card').scrollIntoViewIfNeeded();
  await page.evaluate(()=>new Promise<void>(resolve=>requestAnimationFrame(()=>resolve())));
  const png=await app.evaluate(async({BrowserWindow})=>(await BrowserWindow.getAllWindows()[0].capturePage(undefined,{stayHidden:true,stayAwake:true})).toPNG().toString('base64'));
  await writeFile(join(root,'proactive.png'),Buffer.from(png,'base64'));
  await request('/v1/sources/'+memory.record.source_id+'?revision=1','DELETE');
  await expect(page.getByTestId('proactive-card')).toHaveCount(0);
  expect(await page.evaluate(()=>(window as any).kirianDesktop.setClickThrough(true))).toEqual({ok:true});
  expect((await page.evaluate(()=>(window as any).kirianDesktop.getSnapshot())).window.clickThrough).toBe(true);
  await app.evaluate(({powerMonitor})=>{powerMonitor.emit('suspend');powerMonitor.emit('lock-screen');powerMonitor.emit('resume');});
  expect((await page.evaluate(()=>(window as any).kirianDesktop.getSnapshot())).window.clickThrough).toBe(false);
  expect((await page.evaluate(()=>(window as any).kirianDesktop.getProactive())).running).toBe(false);
  expect(await page.evaluate(async()=>{try{await(window as any).kirianDesktop.startProactive();return false;}catch{return true;}})).toBe(true);
  await app.evaluate(({powerMonitor})=>powerMonitor.emit('unlock-screen'));
  expect((await page.evaluate(()=>(window as any).kirianDesktop.getProactive())).running).toBe(false);
  await app.close();app=await launch();page=await app.firstWindow();
  await page.evaluate(options=>(window as any).kirianDesktop.connectBrain(options),{url:brain.url,token:brain.token});
  await expect(page.getByTestId('connection-status')).toHaveText('연결됨');
  expect((await page.evaluate(()=>(window as any).kirianDesktop.getProactive())).running).toBe(false);expect(requests.length).toBe(1);
 }finally{await app?.close();await brain.stop();await new Promise<void>(r=>upstream.close(()=>r()));}
});
